# Generated by Django 2.1.2 on 2019-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player_score', models.IntegerField(default=0)),
                ('right_player_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Scores',
                'ordering': ['created_at'],
                'verbose_name': 'Score',
            },
        ),
    ]
